dynamic package cache update

diff --git a/.github/workflows/blocklists_update.yml b/.github/workflows/blocklists_update.yml
--- a/.github/workflows/blocklists_update.yml
+++ b/.github/workflows/blocklists_update.yml
@@ -35,10 +35,20 @@ jobs:
           source .venv_blocklist/bin/activate
           pip install requests ipaddress geoip2 path
         else
-          echo "Using cached virtualenv"
+          installed_packages=$(pip freeze)
+          required_packages=("requests" "ipaddress" "geoip2" "path")
+      
+          for package in "${required_packages[@]}"; do
+            if ! echo "$installed_packages" | grep -q "^${package}=="; then
+              echo "Missing or incorrect $package. Installing the required packages."
+              pip install requests ipaddress geoip2 path
+              break
+            fi
+          done
         fi
         echo "$PWD/.venv_blocklist/bin" >> $GITHUB_PATH
         echo "VIRTUAL_ENV=$PWD/.venv_blocklist" >> $GITHUB_ENV
+      
     
     - name: Save cached virtualenv
       uses: actions/cache@v4
